### ISSUE TITLE
Yaml generation for 0.22

### ISSUE THREAD

**Issue by ichihito-ohi** [ichihito-ohi/PhantomBrigade-Translation#66]
Patch 0.22.0 changed the folder structure for the text files; `Text/` folder was removed and `TextLibrary/` folder is added.
According to the build-in localization (French and German,) yaml file in `<lang>/Sectors/` folder should have just `text:` entries.
```yaml
entries:
    entry_1:
        text: "Translation"
    
    # Brank entry
    entry_2:
        text:
````
Like present German, brank entry overrides text, and even the original text won't be shown in game.
So, the script has to generate YAML containing only entries with translated text.
